project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://nakatsukaryota.github.io/ # you must change this appropriately for RSS feeds to work properly
  title: "Ryota's Notes"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
